# 1. workflow name
name: shell commands

# 2. event trigger
on: [push]

# 3.
jobs:
  # <job 1> 'run-shell-command'
  run-shell-command:
    # os to run on
    runs-on: ubuntu-latest
    # list of steps to perform
    steps:
      - name: step1 - print messg
        run: echo "Hello World"
      - name: step2 - multiline script
        run: |
          node -v
          npm -v
      - name: step3 - python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  # <job 2> 'run-shell-command'
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: step 1 - directory powerShell - default
        run: Get-Location
      - name: step 1 - directory bash
        shell: bash
        run: pwd
